///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HoroscopeModel {
/*
{
  "current_date": "June 23, 2017",
  "compatibility": " Cancer",
  "lucky_time": " 7am",
  "lucky_number": " 64",
  "color": " Spring Green",
  "date_range": "Mar 21 - Apr 20",
  "mood": " Relaxed",
  "description": "It's finally time for you to think about just one thing: what makes you happy. Fortunately, that happens to be a person who feels the same way. Give yourself the evening off. Refuse to be put in charge of anything."
} 
*/
  String? name;
  String? currentDate;
  String? compatibility;
  String? luckyTime;
  String? luckyNumber;
  String? color;
  String? dateRange;
  String? mood;
  String? description;

  HoroscopeModel({
    this.name,
    this.currentDate,
    this.compatibility,
    this.luckyTime,
    this.luckyNumber,
    this.color,
    this.dateRange,
    this.mood,
    this.description,
  });
  HoroscopeModel.fromJson(Map<String, dynamic> json) {
    currentDate = json['current_date']?.toString();
    compatibility = json['compatibility']?.toString();
    luckyTime = json['lucky_time']?.toString();
    luckyNumber = json['lucky_number']?.toString();
    color = json['color']?.toString();
    dateRange = json['date_range']?.toString();
    mood = json['mood']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_date'] = currentDate;
    data['compatibility'] = compatibility;
    data['lucky_time'] = luckyTime;
    data['lucky_number'] = luckyNumber;
    data['color'] = color;
    data['date_range'] = dateRange;
    data['mood'] = mood;
    data['description'] = description;
    return data;
  }
}
